export const sellerSnapshot = {
  profile: {
    name: 'Priya Nair',
    sellerId: 'SLR-1001',
    area: 'Kolhapur, Maharashtra',
    phone: '+91 98765 43210',
    email: 'priya.nair@irasathi.com',
    assignedVendor: 'Green Valley Hub',
    commissionRate: '2% - 3%',
    cashbackRate: '2.5%',
  },
  overview: {
    walletBalance: '₹18,450',
    monthlyTarget: '₹32 L',
    targetProgress: 68, // percentage
    totalReferrals: 212,
    totalSales: '₹21.6 L',
    thisMonthSales: '₹4.8 L',
    thisMonthReferrals: 18,
    status: 'On Track',
  },
  highlights: [
    { id: 'referrals', label: 'Total Referrals', value: '212', trend: '+18 this month' },
    { id: 'sales', label: 'Total Sales', value: '₹21.6 L', trend: '+12% vs last month' },
    { id: 'target', label: 'Target Progress', value: '68%', trend: 'On track to achieve' },
    { id: 'wallet', label: 'Wallet Balance', value: '₹18,450', trend: 'Available to withdraw' },
  ],
  commissionPolicy: {
    currentMonth: 'January 2025',
    resetDay: 1,
    lastReset: '2025-01-01',
    slabs: [
      { label: 'Up to ₹50,000 per user (monthly)', rate: '2%' },
      { label: 'Above ₹50,000 per user (monthly)', rate: '3%' },
    ],
  },
  recentActivity: [
    {
      id: 'act-1',
      user: 'Anand Kumar',
      action: 'New purchase',
      amount: '+₹2,400',
      commission: '+₹120',
      status: 'Completed',
      date: '2 hours ago',
      avatar: 'AK',
    },
    {
      id: 'act-2',
      user: 'Mita Shah',
      action: 'Order delivered',
      amount: '+₹1,850',
      commission: '+₹92.50',
      status: 'Completed',
      date: '5 hours ago',
      avatar: 'MS',
    },
    {
      id: 'act-3',
      user: 'Rajesh Patel',
      action: 'New referral',
      amount: '₹0',
      commission: 'Pending',
      status: 'Registered',
      date: '1 day ago',
      avatar: 'RP',
    },
    {
      id: 'act-4',
      user: 'Suresh Mehta',
      action: 'Order delivered',
      amount: '+₹3,200',
      commission: '+₹160',
      status: 'Completed',
      date: '1 day ago',
      avatar: 'SM',
    },
    {
      id: 'act-5',
      user: 'Kavita Desai',
      action: 'New purchase',
      amount: '+₹1,500',
      commission: '+₹75',
      status: 'Completed',
      date: '2 days ago',
      avatar: 'KD',
    },
    {
      id: 'act-6',
      user: 'Rohit Sharma',
      action: 'New referral',
      amount: '₹0',
      commission: 'Pending',
      status: 'Registered',
      date: '2 days ago',
      avatar: 'RS',
    },
    {
      id: 'act-7',
      user: 'Neha Gupta',
      action: 'Order delivered',
      amount: '+₹2,800',
      commission: '+₹140',
      status: 'Completed',
      date: '3 days ago',
      avatar: 'NG',
    },
    {
      id: 'act-8',
      user: 'Vikram Singh',
      action: 'New purchase',
      amount: '+₹4,500',
      commission: '+₹225',
      status: 'Completed',
      date: '3 days ago',
      avatar: 'VS',
    },
    {
      id: 'act-9',
      user: 'Priya Reddy',
      action: 'Order delivered',
      amount: '+₹1,200',
      commission: '+₹60',
      status: 'Completed',
      date: '4 days ago',
      avatar: 'PR',
    },
    {
      id: 'act-10',
      user: 'Amit Joshi',
      action: 'New purchase',
      amount: '+₹3,600',
      commission: '+₹180',
      status: 'Completed',
      date: '4 days ago',
      avatar: 'AJ',
    },
    {
      id: 'act-11',
      user: 'Deepa Iyer',
      action: 'Order delivered',
      amount: '+₹2,100',
      commission: '+₹105',
      status: 'Completed',
      date: '5 days ago',
      avatar: 'DI',
    },
    {
      id: 'act-12',
      user: 'Manish Kumar',
      action: 'New referral',
      amount: '₹0',
      commission: 'Pending',
      status: 'Registered',
      date: '5 days ago',
      avatar: 'MK',
    },
    {
      id: 'act-13',
      user: 'Sunita Verma',
      action: 'New purchase',
      amount: '+₹2,900',
      commission: '+₹145',
      status: 'Completed',
      date: '6 days ago',
      avatar: 'SV',
    },
    {
      id: 'act-14',
      user: 'Arjun Nair',
      action: 'Order delivered',
      amount: '+₹1,800',
      commission: '+₹90',
      status: 'Completed',
      date: '1 week ago',
      avatar: 'AN',
    },
    {
      id: 'act-15',
      user: 'Lakshmi Menon',
      action: 'New purchase',
      amount: '+₹3,400',
      commission: '+₹170',
      status: 'Completed',
      date: '1 week ago',
      avatar: 'LM',
    },
  ],
  referrals: [
    {
      id: 'ref-1',
      userId: 'USR-6621',
      name: 'Anand Kumar',
      registeredDate: '2024-11-15',
      totalPurchases: 8,
      totalAmount: '₹48,600',
      monthlyPurchases: 68450,
      lastPurchase: '2 hours ago',
      status: 'Active',
      avatar: 'AK',
    },
    {
      id: 'ref-2',
      userId: 'USR-6622',
      name: 'Mita Shah',
      registeredDate: '2024-11-10',
      totalPurchases: 5,
      totalAmount: '₹32,400',
      monthlyPurchases: 32400,
      lastPurchase: '5 hours ago',
      status: 'Active',
      avatar: 'MS',
    },
    {
      id: 'ref-3',
      userId: 'USR-6623',
      name: 'Rajesh Patel',
      registeredDate: '2024-12-01',
      totalPurchases: 0,
      totalAmount: '₹0',
      monthlyPurchases: 0,
      lastPurchase: 'Never',
      status: 'Registered',
      avatar: 'RP',
    },
  ],
  wallet: {
    balance: '₹18,450',
    pending: '₹2,120',
    totalEarned: '₹1,24,300',
    transactions: [
      {
        id: 'txn-1',
        type: 'commission',
        description: 'Commission from Anand Kumar',
        amount: '+₹120',
        date: '2024-12-15T10:30:00',
        status: 'Completed',
      },
      {
        id: 'txn-2',
        type: 'commission',
        description: 'Commission from Mita Shah',
        amount: '+₹92.50',
        date: '2024-12-15T07:15:00',
        status: 'Completed',
      },
      {
        id: 'txn-3',
        type: 'withdrawal',
        description: 'Withdrawal to bank account',
        amount: '-₹5,000',
        date: '2024-12-10T14:20:00',
        status: 'Completed',
      },
      {
        id: 'txn-4',
        type: 'commission',
        description: 'Commission from multiple users',
        amount: '+₹450',
        date: '2024-12-08T16:45:00',
        status: 'Completed',
      },
    ],
  },
  announcements: [
    {
      id: 'ann-1',
      title: 'New Commission Structure',
      message: 'Starting next month, commission rates will be updated. Check your profile for details.',
      date: '2024-12-14',
      type: 'policy',
      read: false,
    },
    {
      id: 'ann-2',
      title: 'Monthly Target Update',
      message: 'Your target for January 2025 has been set to ₹35 L. Keep up the great work!',
      date: '2024-12-12',
      type: 'target',
      read: false,
    },
    {
      id: 'ann-3',
      title: 'Withdrawal Process Improved',
      message: 'Withdrawal requests will now be processed within 24 hours. Minimum amount is ₹5,000.',
      date: '2024-12-10',
      type: 'update',
      read: true,
    },
  ],
}

