export const userSnapshot = {
  profile: {
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@example.com',
    phone: '+91 98765 43210',
    location: {
      address: '123 Farm Road',
      city: 'Kolhapur',
      state: 'Maharashtra',
      pincode: '416001',
      coordinates: { lat: 16.7050, lng: 74.2433 },
    },
  },
  categories: [
    {
      id: 'organic',
      name: 'Organic',
      emoji: '🌱',
      icon: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=200&h=200&fit=crop',
      count: 45,
      description: 'Organic fertilizers and pesticides',
    },
    {
      id: 'chemical',
      name: 'Chemical',
      emoji: '🧪',
      icon: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=200&h=200&fit=crop',
      count: 78,
      description: 'Chemical fertilizers and pesticides',
    },
    {
      id: 'seeds',
      name: 'Seeds',
      emoji: '🌾',
      icon: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=200&h=200&fit=crop',
      count: 120,
      description: 'High quality seeds for farming',
    },
    {
      id: 'insecticides',
      name: 'Insecticides',
      emoji: '🐛',
      icon: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=200&h=200&fit=crop',
      count: 56,
      description: 'Effective insecticides for crop protection',
    },
    {
      id: 'tools',
      name: 'Tools',
      emoji: '🔧',
      icon: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=200&h=200&fit=crop',
      count: 34,
      description: 'Essential farming equipment',
    },
    {
      id: 'irrigation',
      name: 'Irrigation',
      emoji: '💧',
      icon: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=200&h=200&fit=crop',
      count: 28,
      description: 'Irrigation systems and accessories',
    },
  ],
  banners: [
    {
      id: 'banner-1',
      title: 'Seasonal Sale',
      subtitle: 'Up to 30% off on all fertilizers',
      image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800',
      link: '/category/chemical',
    },
    {
      id: 'banner-2',
      title: 'New Arrivals',
      subtitle: 'Premium organic seeds now available',
      image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800',
      link: '/category/seeds',
    },
    {
      id: 'banner-3',
      title: 'Free Delivery',
      subtitle: 'On orders above ₹5,000',
      image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800',
      link: '/offers',
    },
  ],
  products: [
    {
      id: 'prod-1',
      name: 'NPK 19:19:19 Fertilizer',
      description: 'Balanced NPK fertilizer for all crops. Promotes healthy growth and high yield.',
      price: 1250,
      originalPrice: 1500,
      discount: 17,
      image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400',
      category: 'chemical',
      stock: 45,
      rating: 4.5,
      reviews: 128,
      vendor: {
        id: 'vendor-1',
        name: 'Green Valley Hub',
        location: 'Kolhapur, Maharashtra',
        distance: '2.5 km',
      },
      deliveryTime: '3 hours',
      isWishlisted: false,
    },
    {
      id: 'prod-2',
      name: 'Organic Compost 50kg',
      description: 'Premium organic compost made from farm waste. 100% natural and chemical-free.',
      price: 850,
      originalPrice: 1000,
      discount: 15,
      image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400',
      category: 'organic',
      stock: 32,
      rating: 4.8,
      reviews: 95,
      vendor: {
        id: 'vendor-2',
        name: 'Farm Fresh Traders',
        location: 'Kolhapur, Maharashtra',
        distance: '5.2 km',
      },
      deliveryTime: '4 hours',
      isWishlisted: true,
    },
    {
      id: 'prod-3',
      name: 'Hybrid Tomato Seeds',
      description: 'High-yield hybrid tomato seeds. Disease resistant and suitable for all seasons.',
      price: 450,
      originalPrice: 500,
      discount: 10,
      image: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=400',
      category: 'seeds',
      stock: 8,
      rating: 4.6,
      reviews: 203,
      vendor: {
        id: 'vendor-1',
        name: 'Green Valley Hub',
        location: 'Kolhapur, Maharashtra',
        distance: '2.5 km',
      },
      deliveryTime: '3 hours',
      isWishlisted: false,
    },
    {
      id: 'prod-4',
      name: 'Neem Oil Insecticide',
      description: 'Natural neem oil based insecticide. Safe for plants and environment.',
      price: 680,
      originalPrice: 750,
      discount: 9,
      image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400',
      category: 'insecticides',
      stock: 0,
      rating: 4.4,
      reviews: 87,
      vendor: {
        id: 'vendor-2',
        name: 'Farm Fresh Traders',
        location: 'Kolhapur, Maharashtra',
        distance: '5.2 km',
      },
      deliveryTime: '4 hours',
      isWishlisted: false,
    },
    {
      id: 'prod-5',
      name: 'Urea 46-0-0 Fertilizer',
      description: 'High nitrogen content urea fertilizer. Ideal for vegetative growth stage.',
      price: 920,
      originalPrice: 1100,
      discount: 16,
      image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400',
      category: 'chemical',
      stock: 67,
      rating: 4.3,
      reviews: 156,
      vendor: {
        id: 'vendor-1',
        name: 'Green Valley Hub',
        location: 'Kolhapur, Maharashtra',
        distance: '2.5 km',
      },
      deliveryTime: '3 hours',
      isWishlisted: false,
    },
    {
      id: 'prod-6',
      name: 'Wheat Seeds Premium',
      description: 'Premium quality wheat seeds with high germination rate. Suitable for rabi season.',
      price: 550,
      originalPrice: 600,
      discount: 8,
      image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400',
      category: 'seeds',
      stock: 25,
      rating: 4.7,
      reviews: 189,
      vendor: {
        id: 'vendor-2',
        name: 'Farm Fresh Traders',
        location: 'Kolhapur, Maharashtra',
        distance: '5.2 km',
      },
      deliveryTime: '4 hours',
      isWishlisted: true,
    },
  ],
  popularProducts: [
    'prod-1',
    'prod-2',
    'prod-3',
    'prod-5',
  ],
  deals: [
    {
      id: 'deal-1',
      title: 'Buy 2 Get 1 Free',
      subtitle: 'On all organic products',
      category: 'organic',
    },
    {
      id: 'deal-2',
      title: 'Flat 20% Off',
      subtitle: 'On orders above ₹5,000',
      category: null,
    },
    {
      id: 'deal-3',
      title: 'Free Delivery',
      subtitle: 'For orders above ₹2,000',
      category: null,
    },
  ],
  orders: [
    {
      id: 'ORD-001',
      date: '2024-12-15',
      status: 'delivered',
      paymentStatus: 'fully_paid',
      items: [
        { productId: 'prod-1', name: 'NPK 19:19:19 Fertilizer', quantity: 2, price: 1250 },
        { productId: 'prod-3', name: 'Hybrid Tomato Seeds', quantity: 1, price: 450 },
      ],
      total: 2950,
      advancePaid: 885,
      remaining: 2065,
      vendor: {
        id: 'vendor-1',
        name: 'Green Valley Hub',
        location: 'Kolhapur, Maharashtra',
      },
      deliveryTime: 'Delivered on Dec 15, 09:45 AM',
      statusTimeline: [
        { status: 'awaiting', timestamp: '2024-12-15T06:15:00' },
        { status: 'dispatched', timestamp: '2024-12-15T07:30:00' },
        { status: 'delivered', timestamp: '2024-12-15T09:45:00' },
      ],
      deliveryDate: '2024-12-15',
    },
    {
      id: 'ORD-002',
      date: '2024-12-18',
      status: 'dispatched',
      paymentStatus: 'partial_paid',
      items: [
        { productId: 'prod-2', name: 'Organic Compost 50kg', quantity: 3, price: 850 },
      ],
      total: 2550,
      advancePaid: 765,
      remaining: 1785,
      vendor: {
        id: 'vendor-2',
        name: 'Farm Fresh Traders',
        location: 'Kolhapur, Maharashtra',
      },
      deliveryTime: 'On the way - arriving within 24 hours',
      statusTimeline: [
        { status: 'awaiting', timestamp: '2024-12-18T08:10:00' },
        { status: 'dispatched', timestamp: '2024-12-18T11:30:00' },
      ],
      deliveryDate: null,
    },
    {
      id: 'ORD-003',
      date: '2024-12-20',
      status: 'awaiting',
      paymentStatus: 'pending',
      items: [
        { productId: 'prod-5', name: 'Urea 46-0-0 Fertilizer', quantity: 1, price: 920 },
      ],
      total: 920,
      advancePaid: 0,
      remaining: 920,
      vendor: null,
      deliveryTime: 'Awaiting vendor confirmation',
      statusTimeline: [
        { status: 'awaiting', timestamp: '2024-12-20T10:05:00' },
      ],
      deliveryDate: null,
    },
  ],
  addresses: [
    {
      id: 'addr-1',
      name: 'Home',
      address: '123 Farm Road',
      city: 'Kolhapur',
      state: 'Maharashtra',
      pincode: '416001',
      phone: '+91 98765 43210',
      isDefault: true,
    },
    {
      id: 'addr-2',
      name: 'Farm',
      address: '456 Agricultural Land',
      city: 'Kolhapur',
      state: 'Maharashtra',
      pincode: '416002',
      phone: '+91 98765 43210',
      isDefault: false,
    },
  ],
}

export const MIN_ORDER_VALUE = 2000
export const ADVANCE_PAYMENT_PERCENTAGE = 30
export const REMAINING_PAYMENT_PERCENTAGE = 70

